# Generated by Django 3.2.4 on 2022-04-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('dni', models.IntegerField(max_length=8)),
                ('direccion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Contribuyente',
                'verbose_name_plural': 'Contribuyentes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('nivel_acceso', models.IntegerField(max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.contribuyente')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_usuario'],
            },
        ),
        migrations.CreateModel(
            name='Fallecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fallecimiento', models.DateField()),
                ('fallecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.contribuyente')),
            ],
            options={
                'verbose_name': 'Fallecido',
                'verbose_name_plural': 'Fallecidos',
                'ordering': ['fallecido'],
            },
        ),
    ]
