# Generated by Django 3.2.4 on 2022-04-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acceso',
            field=models.IntegerField(),
        ),
    ]
