# Generated by Django 3.2.4 on 2022-04-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20220427_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficinaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina_registro', models.CharField(max_length=100)),
                ('departamento_registro', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Of.Registro',
                'verbose_name_plural': 'Ofs.Registro',
                'ordering': ['departamento_registro'],
            },
        ),
        migrations.CreateModel(
            name='PermisoInhumacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_en_registro', models.DateField()),
                ('fecha_presentacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('fallecido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.fallecido')),
                ('oficina_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.oficinaregistro')),
                ('presentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.contribuyente')),
            ],
            options={
                'verbose_name': 'Perm.Inhum',
                'verbose_name_plural': 'Perms.Inhum',
                'ordering': ['fecha_presentacion'],
            },
        ),
    ]
