# Generated by Django 3.2.4 on 2022-04-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_oficinaregistro_permisoinhumacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cant_anios', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Periodicidad',
                'verbose_name_plural': 'Periodicidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.IntegerField()),
                ('monto_tasa', models.FloatField()),
                ('monto_recargo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.FloatField()),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('periodicidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.periodicidad')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.zona')),
            ],
            options={
                'verbose_name': 'Tasa',
                'verbose_name_plural': 'Tasas',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fila', models.IntegerField()),
                ('sector', models.CharField(max_length=20)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.zona')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
    ]
